export const PLANTS = [
    {
        id: '1',
        name: 'Pepper Plant',
        price: 5.99,
        originalPrice: 8.99,
        rating: 4.8,
        reviews: 1200,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1611735341450-74d61e660ad2?auto=format&fit=crop&w=400&q=80',
        description: 'A beautiful indoor pepper plant. Thrives in bright indirect sunlight.',
        isFavorite: false,
        sizes: ['S', 'M', 'L', 'XL'],
    },
    {
        id: '2',
        name: 'ZZ Plant',
        price: 12.99,
        originalPrice: 17.99,
        rating: 4.7,
        reviews: 950,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&w=400&q=80',
        description: 'ZZ Plant is known for its wide, attractive, dark green leaves. Practically indestructible.',
        isFavorite: true,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '3',
        name: 'Calathea Zebra',
        price: 9.99,
        originalPrice: 14.99,
        rating: 4.5,
        reviews: 750,
        category: 'Outdoor',
        image: 'https://images.unsplash.com/photo-1612690669207-fed642192c40?auto=format&fit=crop&w=400&q=80',
        description: 'Calathea zebrina has bold striped foliage and is known as a prayer plant.',
        isFavorite: false,
        sizes: ['S', 'M'],
    },
    {
        id: '4',
        name: 'Alright Cactus',
        price: 3.99,
        originalPrice: 6.99,
        rating: 4.9,
        reviews: 2100,
        category: 'Outdoor',
        image: 'https://images.unsplash.com/photo-1464272006398-0baa5b3c4117?auto=format&fit=crop&w=400&q=80',
        description: 'A hardy desert cactus, perfect for bright sunny spots. Very low maintenance.',
        isFavorite: false,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '5',
        name: 'Rubber Fig Plant',
        price: 15.99,
        originalPrice: 21.99,
        rating: 4.6,
        reviews: 880,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=400&q=80',
        description: 'The rubber plant tree is a bold specimen with large, glossy leaves.',
        isFavorite: true,
        sizes: ['M', 'L', 'XL'],
    },
    {
        id: '6',
        name: 'Succulent Mix',
        price: 7.49,
        originalPrice: 10.99,
        rating: 4.4,
        reviews: 630,
        category: 'Outdoor',
        image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=400&q=80',
        description: 'A beautiful mixed succulent arrangement perfect for desks and shelves.',
        isFavorite: false,
        sizes: ['S', 'M'],
    },
    {
        id: '7',
        name: 'Peace Lily',
        price: 11.49,
        originalPrice: 15.99,
        rating: 4.7,
        reviews: 1450,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1593482892290-f54927ae1bb8?auto=format&fit=crop&w=400&q=80',
        description: 'Peace lilies are easy-growing plants that also clean the air.',
        isFavorite: false,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '8',
        name: 'Monstera Deliciosa',
        price: 18.99,
        originalPrice: 25.99,
        rating: 4.9,
        reviews: 3200,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1572688484438-313a6a50be7c?auto=format&fit=crop&w=400&q=80',
        description: 'The iconic Swiss cheese plant. Perfect statement piece for any room.',
        isFavorite: true,
        sizes: ['M', 'L', 'XL'],
    },
];

export const CATEGORIES = [
    { id: 'all', label: 'All' },
    { id: 'indoor', label: 'Indoor' },
    { id: 'outdoor', label: 'Outdoor' },
    { id: 'succulents', label: 'Succulents' },
    { id: 'trees', label: 'Trees' },
];

export const NOTIFICATIONS = [
    {
        id: '1',
        type: 'order',
        icon: 'bag-handle-outline',
        title: 'Flayfully Added Succelent',
        message: 'Your product has been successfully added to the cart!',
        time: '2 min ago',
        isRead: false,
    },
    {
        id: '2',
        type: 'order',
        icon: 'cube-outline',
        title: 'Delivery Successful!',
        message: 'Your order has been successfully delivered. Thank you!',
        time: '10 min ago',
        isRead: false,
    },
    {
        id: '3',
        type: 'promo',
        icon: 'pricetag-outline',
        title: 'Get 30% Off! Today Only!',
        message: 'Get 30% off on all plants today only. Don\'t miss it!',
        time: '1 hour ago',
        isRead: true,
    },
    {
        id: '4',
        type: 'order',
        icon: 'star-outline',
        title: 'Rate Your Purchase!',
        message: 'How was your ZZ Plant? Leave a review and get 50 points.',
        time: '3 hours ago',
        isRead: true,
    },
];

export const TRANSACTIONS = [
    {
        id: '1',
        name: 'Prayer Plant',
        date: 'Dec 15, 2024 | 10:00 AM',
        amount: 29.00,
        type: 'Orders',
        icon: 'https://images.unsplash.com/photo-1612690669207-fed642192c40?auto=format&fit=crop&w=100&q=80',
        isTopUp: false,
    },
    {
        id: '2',
        name: 'Top Up Wallet',
        date: 'Dec 14, 2024 | 16:42 PM',
        amount: 100.00,
        type: 'Top Up',
        icon: null,
        isTopUp: true,
    },
    {
        id: '3',
        name: 'Rubber Fig Plant',
        date: 'Dec 14, 2024 | 11:39 AM',
        amount: 99.00,
        type: 'Orders',
        icon: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=100&q=80',
        isTopUp: false,
    },
    {
        id: '4',
        name: 'ZZ Plant',
        date: 'Dec 13, 2024 | 14:46 PM',
        amount: 50.00,
        type: 'Orders',
        icon: 'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&w=100&q=80',
        isTopUp: false,
    },
    {
        id: '5',
        name: 'Top Up Wallet',
        date: 'Dec 12, 2024 | 09:27 AM',
        amount: 75.00,
        type: 'Top Up',
        icon: null,
        isTopUp: true,
    },
];
