export const PLANTS = [
    {
        id: '1',
        name: 'Pepper Plant',
        price: 5.99,
        originalPrice: 8.99,
        rating: 4.8,
        reviews: 1200,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1611735341450-74d61e660ad2?auto=format&fit=crop&w=400&q=80',
        description: 'A beautiful indoor pepper plant. Thrives in bright indirect sunlight.',
        isFavorite: false,
        sizes: ['S', 'M', 'L', 'XL'],
    },
    {
        id: '2',
        name: 'ZZ Plant',
        price: 12.99,
        originalPrice: 17.99,
        rating: 4.7,
        reviews: 950,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&w=400&q=80',
        description: 'ZZ Plant is known for its wide, attractive, dark green leaves. Practically indestructible.',
        isFavorite: true,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '3',
        name: 'Calathea Zebra',
        price: 9.99,
        originalPrice: 14.99,
        rating: 4.5,
        reviews: 750,
        category: 'Outdoor',
        image: 'https://images.unsplash.com/photo-1612690669207-fed642192c40?auto=format&fit=crop&w=400&q=80',
        description: 'Calathea zebrina has bold striped foliage and is known as a prayer plant.',
        isFavorite: false,
        sizes: ['S', 'M'],
    },
    {
        id: '4',
        name: 'Alright Cactus',
        price: 3.99,
        originalPrice: 6.99,
        rating: 4.9,
        reviews: 2100,
        category: 'Outdoor',
        image: 'https://images.unsplash.com/photo-1464272006398-0baa5b3c4117?auto=format&fit=crop&w=400&q=80',
        description: 'A hardy desert cactus, perfect for bright sunny spots. Very low maintenance.',
        isFavorite: false,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '5',
        name: 'Rubber Fig Plant',
        price: 15.99,
        originalPrice: 21.99,
        rating: 4.6,
        reviews: 880,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=400&q=80',
        description: 'The rubber plant tree is a bold specimen with large, glossy leaves.',
        isFavorite: true,
        sizes: ['M', 'L', 'XL'],
    },
    {
        id: '6',
        name: 'Succulent Mix',
        price: 7.49,
        originalPrice: 10.99,
        rating: 4.4,
        reviews: 630,
        category: 'Outdoor',
        image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=400&q=80',
        description: 'A beautiful mixed succulent arrangement perfect for desks and shelves.',
        isFavorite: false,
        sizes: ['S', 'M'],
    },
    {
        id: '7',
        name: 'Peace Lily',
        price: 11.49,
        originalPrice: 15.99,
        rating: 4.7,
        reviews: 1450,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1593482892290-f54927ae1bb8?auto=format&fit=crop&w=400&q=80',
        description: 'Peace lilies are easy-growing plants that also clean the air.',
        isFavorite: false,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '8',
        name: 'Monstera Deliciosa',
        price: 18.99,
        originalPrice: 25.99,
        rating: 4.9,
        reviews: 3200,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1572688484438-313a6a50be7c?auto=format&fit=crop&w=400&q=80',
        description: 'The iconic Swiss cheese plant. Perfect statement piece for any room.',
        isFavorite: true,
        sizes: ['M', 'L', 'XL'],
    },
    {
        id: '9',
        name: 'Snake Plant',
        price: 14.50,
        originalPrice: 19.00,
        rating: 4.8,
        reviews: 1800,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1593482892290-f54927ae1bb8?auto=format&fit=crop&w=400&q=80',
        description: 'A stylish and hardy indoor plant that purifies the air.',
        isFavorite: false,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '10',
        name: 'Fiddle Leaf Fig',
        price: 24.99,
        originalPrice: 35.00,
        rating: 4.6,
        reviews: 2100,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1572688484438-313a6a50be7c?auto=format&fit=crop&w=400&q=80',
        description: 'A large, impressive indoor tree with distinctive violin-shaped leaves.',
        isFavorite: true,
        sizes: ['L', 'XL'],
    },
    {
        id: '11',
        name: 'Aloe Vera',
        price: 6.99,
        originalPrice: 9.99,
        rating: 4.7,
        reviews: 1500,
        category: 'Succulents',
        image: 'https://images.unsplash.com/photo-1611735341450-74d61e660ad2?auto=format&fit=crop&w=400&q=80',
        description: 'A versatile succulent known for its soothing gel and medicinal properties.',
        isFavorite: false,
        sizes: ['S', 'M'],
    },
    {
        id: '12',
        name: 'Areca Palm',
        price: 19.99,
        originalPrice: 28.00,
        rating: 4.5,
        reviews: 900,
        category: 'Palm',
        image: 'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&w=400&q=80',
        description: 'A lush, feathery palm that adds a tropical touch to any office or home.',
        isFavorite: false,
        sizes: ['M', 'L', 'XL'],
    },
    {
        id: '13',
        name: 'Jade Plant',
        price: 8.99,
        originalPrice: 12.00,
        rating: 4.9,
        reviews: 1100,
        category: 'Succulents',
        image: 'https://images.unsplash.com/photo-1612690669207-fed642192c40?auto=format&fit=crop&w=400&q=80',
        description: 'A tree-like succulent that symbolises good luck and prosperity.',
        isFavorite: true,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '14',
        name: 'Golden Pothos',
        price: 5.49,
        originalPrice: 8.00,
        rating: 4.8,
        reviews: 2500,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1464272006398-0baa5b3c4117?auto=format&fit=crop&w=400&q=80',
        description: 'A versatile trailing plant with beautiful heart-shaped, variegated leaves.',
        isFavorite: false,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '15',
        name: 'Spider Plant',
        price: 7.99,
        originalPrice: 11.00,
        rating: 4.7,
        reviews: 1300,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=400&q=80',
        description: 'Fun, air-purifying plant with arching leaves that produce small "spiderettes".',
        isFavorite: false,
        sizes: ['S', 'M'],
    },
    {
        id: '16',
        name: 'Boston Fern',
        price: 13.99,
        originalPrice: 19.50,
        rating: 4.4,
        reviews: 800,
        category: 'Outdoor',
        image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=400&q=80',
        description: 'A classic indoor fern with lush, feathery fronds that love humidity.',
        isFavorite: false,
        sizes: ['M', 'L'],
    },
    {
        id: '17',
        name: 'Majesty Palm',
        price: 35.00,
        originalPrice: 45.00,
        rating: 4.2,
        reviews: 450,
        category: 'Palm',
        image: 'https://images.unsplash.com/photo-1611735341450-74d61e660ad2?auto=format&fit=crop&w=400&q=80',
        description: 'A graceful and majestic palm that thrives in bright light and high humidity.',
        isFavorite: false,
        sizes: ['L', 'XL'],
    },
    {
        id: '18',
        name: 'Burros Tail',
        price: 11.00,
        originalPrice: 15.00,
        rating: 4.9,
        reviews: 700,
        category: 'Succulents',
        image: 'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&w=400&q=80',
        description: 'An eye-catching succulent with trailing stems of plump, teardrop leaves.',
        isFavorite: true,
        sizes: ['S', 'M'],
    },
    {
        id: '19',
        name: 'Red Aglaonema',
        price: 16.50,
        originalPrice: 22.00,
        rating: 4.7,
        reviews: 920,
        category: 'Indoor',
        image: 'https://images.unsplash.com/photo-1612690669207-fed642192c40?auto=format&fit=crop&w=400&q=80',
        description: 'A stunning foliage plant with vibrant pink and red splashes on green leaves.',
        isFavorite: false,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '20',
        name: 'Ponytail Palm',
        price: 22.00,
        originalPrice: 30.00,
        rating: 4.8,
        reviews: 650,
        category: 'Palm',
        image: 'https://images.unsplash.com/photo-1464272006398-0baa5b3c4117?auto=format&fit=crop&w=400&q=80',
        description: 'A unique plant with a swollen base and long, wispy hair-like leaves.',
        isFavorite: false,
        sizes: ['M', 'L'],
    },
    {
        id: '21',
        name: 'Bird of Paradise',
        price: 45.99,
        originalPrice: 60.00,
        rating: 4.9,
        reviews: 1200,
        category: 'Trees',
        image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=400&q=80',
        description: 'A spectacular tropical plant known for its large leaves and exotic flowers.',
        isFavorite: true,
        sizes: ['L', 'XL'],
    },
    {
        id: '22',
        name: 'Echeveria Rose',
        price: 5.99,
        originalPrice: 9.00,
        rating: 4.5,
        reviews: 1100,
        category: 'Succulents',
        image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=400&q=80',
        description: 'A beautiful rosette-shaped succulent with delicate pink-tipped leaves.',
        isFavorite: false,
        sizes: ['S', 'M'],
    },
    {
        id: '23',
        name: 'Barrel Cactus',
        price: 18.00,
        originalPrice: 25.00,
        rating: 4.7,
        reviews: 430,
        category: 'Cactus',
        image: 'https://images.unsplash.com/photo-1593482892290-f54927ae1bb8?auto=format&fit=crop&w=400&q=80',
        description: 'A round, rib-covered cactus that makes a perfect accent in sunny rooms.',
        isFavorite: false,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '24',
        name: 'Yucca Cane',
        price: 28.99,
        originalPrice: 40.00,
        rating: 4.4,
        reviews: 320,
        category: 'Trees',
        image: 'https://images.unsplash.com/photo-1572688484438-313a6a50be7c?auto=format&fit=crop&w=400&q=80',
        description: 'A bold, architectural tree that thrives with minimal care and bright light.',
        isFavorite: false,
        sizes: ['M', 'L', 'XL'],
    },
    {
        id: '25',
        name: 'String of Pearls',
        price: 12.49,
        originalPrice: 18.00,
        rating: 4.9,
        reviews: 850,
        category: 'Succulents',
        image: 'https://images.unsplash.com/photo-1611735341450-74d61e660ad2?auto=format&fit=crop&w=400&q=80',
        description: 'A captivating trailing succulent with unique spherical, pearl-like leaves.',
        isFavorite: true,
        sizes: ['S', 'M'],
    },
    {
        id: '26',
        name: 'Parlor Palm',
        price: 10.99,
        originalPrice: 15.00,
        rating: 4.6,
        reviews: 770,
        category: 'Palm',
        image: 'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&w=400&q=80',
        description: 'A compact and elegant palm that tolerates lower light conditions perfectly.',
        isFavorite: false,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '27',
        name: 'Haworthia Zebra',
        price: 4.99,
        originalPrice: 7.00,
        rating: 4.8,
        reviews: 1400,
        category: 'Succulents',
        image: 'https://images.unsplash.com/photo-1612690669207-fed642192c40?auto=format&fit=crop&w=400&q=80',
        description: 'A charming small succulent with striking white horizontal stripes.',
        isFavorite: false,
        sizes: ['S', 'M'],
    },
    {
        id: '28',
        name: 'Money Tree',
        price: 19.49,
        originalPrice: 28.00,
        rating: 4.7,
        reviews: 560,
        category: 'Trees',
        image: 'https://images.unsplash.com/photo-1464272006398-0baa5b3c4117?auto=format&fit=crop&w=400&q=80',
        description: 'Believe to bring good luck with its braided stem and palmate leaves.',
        isFavorite: true,
        sizes: ['M', 'L'],
    },
    {
        id: '29',
        name: 'Saguaro Cactus',
        price: 55.00,
        originalPrice: 75.00,
        rating: 4.9,
        reviews: 210,
        category: 'Cactus',
        image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=400&q=80',
        description: 'The iconic desert cactus. A slow-growing but stunning centerpiece.',
        isFavorite: false,
        sizes: ['L', 'XL'],
    },
    {
        id: '30',
        name: 'Swiss Cheese Vine',
        price: 14.99,
        originalPrice: 21.00,
        rating: 4.8,
        reviews: 1600,
        category: 'Monstera',
        image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=400&q=80',
        description: 'A beautiful climbing or trailing plant with smaller, distinct leaf holes.',
        isFavorite: true,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '31',
        name: 'Prickly Pear',
        price: 9.49,
        originalPrice: 13.00,
        rating: 4.5,
        reviews: 320,
        category: 'Cactus',
        image: 'https://images.unsplash.com/photo-1593482892290-f54927ae1bb8?auto=format&fit=crop&w=400&q=80',
        description: 'A flat-padded cactus that adds a desert charm to your outdoor garden.',
        isFavorite: false,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '32',
        name: 'Monstera Adansonii',
        price: 13.50,
        originalPrice: 19.00,
        rating: 4.7,
        reviews: 890,
        category: 'Monstera',
        image: 'https://images.unsplash.com/photo-1572688484438-313a6a50be7c?auto=format&fit=crop&w=400&q=80',
        description: 'A small-leaved monstera with charming perforations, perfect for hanging.',
        isFavorite: false,
        sizes: ['S', 'M'],
    },
    {
        id: '33',
        name: 'Aloe Arborescens',
        price: 15.99,
        originalPrice: 22.00,
        rating: 4.6,
        reviews: 440,
        category: 'Aloe',
        image: 'https://images.unsplash.com/photo-1611735341450-74d61e660ad2?auto=format&fit=crop&w=400&q=80',
        description: 'A tree-like aloe that produces beautiful vibrant orange flower spikes.',
        isFavorite: false,
        sizes: ['M', 'L'],
    },
    {
        id: '34',
        name: 'Blue Columnar Cactus',
        price: 32.00,
        originalPrice: 42.00,
        rating: 4.9,
        reviews: 180,
        category: 'Cactus',
        image: 'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&w=400&q=80',
        description: 'A tall, stately cactus with a unique bluish hue that stands out in any collection.',
        isFavorite: true,
        sizes: ['L', 'XL'],
    },
    {
        id: '35',
        name: 'Aloe Polyphylla',
        price: 48.00,
        originalPrice: 65.00,
        rating: 4.9,
        reviews: 120,
        category: 'Aloe',
        image: 'https://images.unsplash.com/photo-1612690669207-fed642192c40?auto=format&fit=crop&w=400&q=80',
        description: 'A rare aloe known for its perfect spiral growth pattern. A true collector item.',
        isFavorite: true,
        sizes: ['M', 'L'],
    },
    {
        id: '36',
        name: 'Ruffled Fan Palm',
        price: 40.00,
        originalPrice: 55.00,
        rating: 4.8,
        reviews: 310,
        category: 'Palm',
        image: 'https://images.unsplash.com/photo-1464272006398-0baa5b3c4117?auto=format&fit=crop&w=400&q=80',
        description: 'An exquisite palm with pleated, fan-shaped leaves that create a stunning texture.',
        isFavorite: false,
        sizes: ['M', 'L', 'XL'],
    },
    {
        id: '37',
        name: 'Dragon Tree',
        price: 21.00,
        originalPrice: 30.00,
        rating: 4.7,
        reviews: 580,
        category: 'Trees',
        image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=400&q=80',
        description: 'A tough, sword-leaved tree that is highly adaptable to various light levels.',
        isFavorite: false,
        sizes: ['M', 'L'],
    },
    {
        id: '38',
        name: 'Christmas Cactus',
        price: 8.49,
        originalPrice: 12.00,
        rating: 4.6,
        reviews: 640,
        category: 'Cactus',
        image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=400&q=80',
        description: 'A popular indoor cactus that blooms beautiful pink flowers in the winter.',
        isFavorite: false,
        sizes: ['S', 'M'],
    },
    {
        id: '39',
        name: 'Monstera Siltepecana',
        price: 17.00,
        originalPrice: 24.00,
        rating: 4.8,
        reviews: 510,
        category: 'Monstera',
        image: 'https://images.unsplash.com/photo-1593482892290-f54927ae1bb8?auto=format&fit=crop&w=400&q=80',
        description: 'Unique monstera with silvery leaves in its juvenile stage and climbing habit.',
        isFavorite: false,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '40',
        name: 'Aloe Brevifolia',
        price: 7.99,
        originalPrice: 11.00,
        rating: 4.5,
        reviews: 320,
        category: 'Aloe',
        image: 'https://images.unsplash.com/photo-1572688484438-313a6a50be7c?auto=format&fit=crop&w=400&q=80',
        description: 'A small, compact aloe with short, decorative leaves that form tight clumps.',
        isFavorite: false,
        sizes: ['S', 'M'],
    },
    {
        id: '41',
        name: 'Kentia Palm',
        price: 55.00,
        originalPrice: 75.00,
        rating: 4.9,
        reviews: 380,
        category: 'Palm',
        image: 'https://images.unsplash.com/photo-1611735341450-74d61e660ad2?auto=format&fit=crop&w=400&q=80',
        description: 'The ultimate luxury palm. Slow-growing and extremely elegant in appearance.',
        isFavorite: true,
        sizes: ['L', 'XL'],
    },
    {
        id: '42',
        name: 'Elephant Foot Tree',
        price: 38.00,
        originalPrice: 50.00,
        rating: 4.8,
        reviews: 190,
        category: 'Trees',
        image: 'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&w=400&q=80',
        description: 'Distinctive tree with a thick, textured base and gracefully arching leaves.',
        isFavorite: false,
        sizes: ['M', 'L'],
    },
    {
        id: '43',
        name: 'Monstera Standleyana',
        price: 22.49,
        originalPrice: 32.00,
        rating: 4.7,
        reviews: 260,
        category: 'Monstera',
        image: 'https://images.unsplash.com/photo-1612690669207-fed642192c40?auto=format&fit=crop&w=400&q=80',
        description: 'A beautiful variegated monstera with speckles of white on dark green leaves.',
        isFavorite: false,
        sizes: ['S', 'M', 'L'],
    },
    {
        id: '44',
        name: 'Aloe Blue Elf',
        price: 11.99,
        originalPrice: 16.00,
        rating: 4.5,
        reviews: 210,
        category: 'Aloe',
        image: 'https://images.unsplash.com/photo-1464272006398-0baa5b3c4117?auto=format&fit=crop&w=400&q=80',
        description: 'A tight-growing aloe that turns a brilliant blue-grey in sunny locations.',
        isFavorite: false,
        sizes: ['S', 'M'],
    },
    {
        id: '45',
        name: 'Fishhook Cactus',
        price: 13.00,
        originalPrice: 18.00,
        rating: 4.6,
        reviews: 150,
        category: 'Cactus',
        image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=400&q=80',
        description: 'A uniquely hooked cactus that is hardy and perfect for modern desert vibes.',
        isFavorite: false,
        sizes: ['S', 'M'],
    },
    {
        id: '46',
        name: 'Silver Lady Fern',
        price: 18.49,
        originalPrice: 26.00,
        rating: 4.4,
        reviews: 230,
        category: 'Outdoor',
        image: 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=400&q=80',
        description: 'A small tree fern with uniform, silvery fronds that love shaded garden spots.',
        isFavorite: false,
        sizes: ['M', 'L'],
    },
    {
        id: '47',
        name: 'Bismarck Palm',
        price: 85.00,
        originalPrice: 110.00,
        rating: 4.9,
        reviews: 90,
        category: 'Palm',
        image: 'https://images.unsplash.com/photo-1593482892290-f54927ae1bb8?auto=format&fit=crop&w=400&q=80',
        description: 'A massive, stunning palm with architectural fans of silvery-blue fronds.',
        isFavorite: true,
        sizes: ['L', 'XL'],
    },
    {
        id: '48',
        name: 'Olive Tree',
        price: 65.00,
        originalPrice: 85.00,
        rating: 4.8,
        reviews: 420,
        category: 'Trees',
        image: 'https://images.unsplash.com/photo-1572688484438-313a6a50be7c?auto=format&fit=crop&w=400&q=80',
        description: 'A Mediterranean classic that adds timeless beauty to any sunlit courtyard.',
        isFavorite: true,
        sizes: ['L', 'XL'],
    },
    {
        id: '49',
        name: 'Monstera Dubia',
        price: 35.00,
        originalPrice: 48.00,
        rating: 4.9,
        reviews: 110,
        category: 'Monstera',
        image: 'https://images.unsplash.com/photo-1611735341450-74d61e660ad2?auto=format&fit=crop&w=400&q=80',
        description: 'The shingle plant. Truly unique growth habit that climbs flat against wood.',
        isFavorite: true,
        sizes: ['S', 'M'],
    },
    {
        id: '50',
        name: 'Giant Saguaro',
        price: 120.00,
        originalPrice: 150.00,
        rating: 5.0,
        reviews: 45,
        category: 'Cactus',
        image: 'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&w=400&q=80',
        description: 'The ultimate desert icon. A centuries-old specimen for the serious collector.',
        isFavorite: true,
        sizes: ['XL'],
    },
];

export const CATEGORIES = [
    { id: 'all', label: 'All' },
    { id: 'Indoor', label: 'Indoor' },
    { id: 'Outdoor', label: 'Outdoor' },
    { id: 'Succulents', label: 'Succulents' },
    { id: 'Trees', label: 'Trees' },
    { id: 'Palm', label: 'Palm' },
    { id: 'Cactus', label: 'Cactus' },
    { id: 'Monstera', label: 'Monstera' },
    { id: 'Aloe', label: 'Aloe' },
];

export const NOTIFICATIONS = [
    {
        id: '1',
        type: 'order',
        icon: 'bag-handle-outline',
        title: 'Successfully Added!',
        message: 'Your product has been successfully added to the cart!',
        time: '2 min ago',
        isRead: false,
    },
    {
        id: '2',
        type: 'order',
        icon: 'cube-outline',
        title: 'Delivery Successful!',
        message: 'Your order of Olive Tree has been delivered. Thank you!',
        time: '10 min ago',
        isRead: false,
    },
    {
        id: '3',
        type: 'promo',
        icon: 'pricetag-outline',
        title: 'Flash Sale! 30% Off!',
        message: 'Get 30% off on all Monstera varieties today only!',
        time: '1 hour ago',
        isRead: true,
    },
    {
        id: '4',
        type: 'order',
        icon: 'star-outline',
        title: 'Rate Your Purchase!',
        message: 'How was your ZZ Plant? Leave a review and get 50 points.',
        time: '3 hours ago',
        isRead: true,
    },
];

export const TRANSACTIONS = [
    {
        id: '1',
        name: 'Giant Saguaro',
        date: 'Dec 15, 2024 | 10:00 AM',
        amount: 120.00,
        type: 'Orders',
        icon: 'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&w=100&q=80',
        isTopUp: false,
    },
    {
        id: '2',
        name: 'Top Up Wallet',
        date: 'Dec 14, 2024 | 16:42 PM',
        amount: 500.00,
        type: 'Top Up',
        icon: null,
        isTopUp: true,
    },
    {
        id: '3',
        name: 'Bismarck Palm',
        date: 'Dec 14, 2024 | 11:39 AM',
        amount: 85.00,
        type: 'Orders',
        icon: 'https://images.unsplash.com/photo-1593482892290-f54927ae1bb8?auto=format&fit=crop&w=100&q=80',
        isTopUp: false,
    },
    {
        id: '4',
        name: 'Olive Tree',
        date: 'Dec 13, 2024 | 14:46 PM',
        amount: 65.00,
        type: 'Orders',
        icon: 'https://images.unsplash.com/photo-1572688484438-313a6a50be7c?auto=format&fit=crop&w=100&q=80',
        isTopUp: false,
    },
    {
        id: '5',
        name: 'Top Up Wallet',
        date: 'Dec 12, 2024 | 09:27 AM',
        amount: 200.00,
        type: 'Top Up',
        icon: null,
        isTopUp: true,
    },
];
